layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
   sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  instagram: MrReekoTV
  twitter: MrReekoTV
  youtube: MrReekoTV

topics:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png

  - name: IDA
    web_url: https://hex-rays.com/ida-pro/
    image_url: https://software-sources.com/wp-content/uploads/2018/05/logo-1.png


